export const initialInventory = [
  { id: 1, name: 'EVERFRSH.& -50', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 2, name: '65 MAIDA', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 3, name: 'KKK MAIDA S & p Maida', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 4, name: 'MARO CREAM', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 5, name: 'ALFACOOKIES', openingStock: 100, received: 0, consumed: 0, unit: 'pcs' },
  { id: 6, name: 'AMRIT', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 7, name: 'GOLD MOHAR', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 8, name: 'ALFAGREEN', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 9, name: 'LILY LITE (1kg)', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 10, name: 'G.S.M (15kg)', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 11, name: 'LOTUS (15kg)', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 12, name: 'GOLD DROP-(13.5kg)', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 13, name: 'SP MAIDA', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 14, name: 'STELLA', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 15, name: 'G.SUGAR-50', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 16, name: 'M.SUGAR', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 17, name: 'AMUL SPARY - 12', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 18, name: 'IMLI', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 19, name: 'MILK MATE -2(15kg)', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 20, name: 'GOOD LIFE-12', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 21, name: 'JAM', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 22, name: 'FRUIT -15 kg', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 23, name: 'GLOBE CORN FLOUR(25)', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 24, name: 'CUSTARD ( WEIKFIELD)', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 25, name: '(Weikfield Corn) FLOOR', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 26, name: 'CORN FLAKES', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 27, name: 'CHOCO EGGLESS', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 28, name: 'PILLS BERRY', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 29, name: 'VANILLA EGGLESS', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 30, name: 'BADAM', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 31, name: '2 PIECE KAJU', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 32, name: '4 PIECE KAJU', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 33, name: 'CH. KHOPRA-25', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 34, name: 'WHITE CHOBA-1kg', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 35, name: 'WHITE TILL', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 36, name: 'KALI TILL', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 37, name: 'GLUCOSE(45 kg BOX)', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 38, name: 'CALCIUM POWDER', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 39, name: 'FINAGEL', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 40, name: 'COCO POWDER', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 41, name: 'RAISEN (KISHMISH)', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 42, name: 'ORANGE', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 43, name: 'LEMON', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 44, name: 'PINEAPPLE', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 45, name: 'AMMONIA', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 46, name: 'TARBOOJ KE BEENJ', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 47, name: 'CHERRY', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 48, name: 'DRY YEAST-500g', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 49, name: 'EGG - 30 per/tray', openingStock: 100, received: 0, consumed: 0, unit: 'tray' },
  { id: 50, name: 'CH METHI', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 51, name: 'TESTING SALT', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 52, name: 'HARA BATASHA', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 53, name: 'VENIGAR', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 54, name: 'BREAD IMPROVER', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 55, name: 'HALDI', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 56, name: 'JEERA', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 57, name: 'ZEERA POWDER', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 58, name: 'GINGER PASTE -5KG BOX', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 59, name: 'RED MIRCHI', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 60, name: 'KALI MIRCH', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 61, name: 'CHART MASALA', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 62, name: 'CHICKEN MASALA', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 63, name: 'GARAM MASALA', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 64, name: 'SALT -25 KG', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 65, name: 'ELAICHI', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 66, name: 'dhania powder', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 67, name: 'CHILLY SAUCE', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 68, name: 'VANILLA POW 20 kg', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 69, name: 'VANILLA ESSENCE(NIRRA)', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 70, name: 'Vanilla Essence', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 71, name: 'Chocolate essence', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 72, name: 'BANANA ESSENCE', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 73, name: 'Bulgarian rose', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 74, name: 'Tooty fruity', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 75, name: 'PINEAPPLE ESSENCE', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 76, name: 'MIXED FRUIT ESSENCE', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 77, name: 'CHOCLATE ESSENCE', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 78, name: 'Rose essence', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 79, name: 'color Yellow', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 80, name: 'orange', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 81, name: 'CARAMEL COLOR', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 82, name: 'biscuit flavor', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 83, name: 'MILK ESSENCE', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 84, name: 'ghee flower', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 85, name: 'MATCH BOX', openingStock: 100, received: 0, consumed: 0, unit: 'box' },
  { id: 86, name: 'WARAQ', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 87, name: 'MAROPRIDE', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 88, name: 'Cake Improver', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 89, name: 'GALOTIN', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 90, name: 'Nageri methi', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  // Added to complete the full 115-item master list
  { id: 91, name: 'GOLD MORE', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 92, name: 'GOOD DAY-25', openingStock: 100, received: 0, consumed: 0, unit: 'pcs' },
  { id: 93, name: 'AMUL.TAAZA-12', openingStock: 100, received: 0, consumed: 0, unit: 'L' },
  { id: 94, name: '16x20', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 95, name: '6x7', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 96, name: 'Masoor Dal', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 97, name: 'CAP', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 98, name: 'SALT -25', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 99, name: 'VANILLA POW 20 kg(RAJ)', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 100, name: 'Table butter', openingStock: 100, received: 0, consumed: 0, unit: 'kg' },
  { id: 101, name: 'butter paper', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 102, name: 'P.P.CoVER- 7 1/2 X 9', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 103, name: 'P.P.CoVER- 7 3/4 X 9', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 104, name: 'P.P.CoVER- 9 X 10 (80)', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 105, name: 'P.P.CoVER- 9 X 10 (150)', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 106, name: 'P.P.CoVER- 8 X 10', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 107, name: 'P.P.CoVER- 8 X 9', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 108, name: 'P.P.CoVER- 8 X 12', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 109, name: 'P.P.CoVER- 6 1/2 X 7', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 110, name: 'P.P.CoVER- 7 X 9', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 111, name: 'P.P.CoVER- 7 X 8', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
  { id: 112, name: 'TAPE -5(1 roll)', openingStock: 100, received: 0, consumed: 0, unit: 'roll' },
  { id: 113, name: '2"', openingStock: 100, received: 0, consumed: 0, unit: 'roll' },
  { id: 114, name: '3"', openingStock: 100, received: 0, consumed: 0, unit: 'roll' },
  { id: 115, name: 'CANDLE-Per Packet/6pcs', openingStock: 100, received: 0, consumed: 0, unit: 'pack' },
];

// Display order derived from the user's sheet. Items not listed here will appear at the end.
export const inventoryOrder = [
  'EVERFRSH.& -50',
  '65 MAIDA',
  'KKK MAIDA S & p Maida',
  'MAROPRIDE',
  'MARO CREAM',
  'ALFACOOKIES',
  'AMRIT',
  'GOLD MOHAR',
  'ALFAGREEN',
  'LILY LITE (1kg)',
  'G.S.M (15kg)',
  'LOTUS (15kg)',
  'GOLD DROP-(13.5kg)',
  'SP MAIDA',
  'STELLA',
  'G.SUGAR-50',
  'M.SUGAR',
  'AMUL SPARY - 12',
  'GOOD DAY-25',
  'MILK MATE -2(15kg)',
  'AMUL.TAAZA-12',
  'GOOD LIFE-12',
  'JAM',
  'FRUIT -15 kg',
  'GLOBE CORN FLOUR(25)',
  'CUSTARD ( WEIKFIELD)',
  '(Weikfield Corn) FLOOR',
  'CORN FLAKES',
  'CHOCO EGGLESS',
  'PILLS BERRY',
  'VANILLA EGGLESS',
  'BADAM',
  '2 PIECE KAJU',
  '4 PIECE KAJU',
  'CH. KHOPRA-25',
  'WHITE CHOBA-1kg',
  'WHITE TILL',
  'KALI TILL',
  'GLUCOSE(45 kg BOX)',
  'CALCIUM POWDER',
  'FINAGEL',
  'COCO POWDER',
  'RAISEN (KISHMISH)',
  'ORANGE',
  'LEMON',
  'AMMONIA',
  'GALOTIN',
  'TARBOOJ KE BEENJ',
  'CHERRY',
  'DRY YEAST-500g',
  'EGG - 30 per/tray',
  'CH METHI',
  'TESTING SALT',
  'HARA BATASHA',
  'VENIGAR',
  'BREAD IMPROVER',
  'HALDI',
  'JEERA',
  'ZEERA POWDER',
  'GINGER PASTE -5KG BOX',
  'RED MIRCHI',
  'KALI MIRCH',
  'CHART MASALA',
  'CHICKEN MASALA',
  'GARAM MASALA',
  'SALT -25 KG',
  'SALT -25',
  'ELAICHI',
  'dhania powder',
  'CHILLY SAUCE',
  'VANILLA POW 20 kg',
  'VANILLA POW 20 kg(RAJ)',
  'Vanilla Essence',
  'Chocolate essence',
  'BANANA ESSENCE',
  'Bulgarian rose',
  'Table butter',
  'MILK ESSENCE',
  'Tooty fruity',
  'PINEAPPLE ESSENCE',
  'MIXED FRUIT ESSENCE',
  'CHOCOLATE ESSENCE',
  'Rose essence',
  'color Yellow',
  'orange',
  'CARAMEL COLOR',
  'biscuit flavor',
  'ghee flower',
  'P.P.CoVER- 7 1/2 X 9',
  'P.P.CoVER- 7 3/4 X 9',
  'P.P.CoVER- 9 X 10 (80)',
  'P.P.CoVER- 9 X 10 (150)',
  'P.P.CoVER- 8 X 10',
  'P.P.CoVER- 8 X 9',
  'P.P.CoVER- 10 X 12',
  'P.P.CoVER- 6 1/2 X 7',
  'P.P.CoVER- 7 X 9',
  'P.P.CoVER- 7 X 8',
  'TAPE -5(1 roll)',
  '2"',
  '3"',
  'MATCH BOX',
  'CANDLE-Per Packet/6pcs',
  '16x20',
  '6x7',
  'Masoor Dal',
  'CAP',
  'Cake Improver',
  'butter paper',
  'Nageri methi',
  'IMLI',
  'WARAQ'
];
